# Generated by Django 5.1.4 on 2025-01-27 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion_diaria', '0003_planificaciondiaria_unique_planificacion_fecha'),
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='planificacion_diaria_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='planificacion_diaria.planificaciondiaria'),
        ),
    ]
