# Generated by Django 5.1.4 on 2025-01-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_alter_recurso_planificacion_diaria_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurso',
            old_name='planificacion_diaria_id',
            new_name='planificacion_diaria',
        ),
        migrations.AlterField(
            model_name='recurso',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
