# Generated by Django 5.1.4 on 2024-12-22 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumno', '0001_initial'),
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificaciones', models.IntegerField(null=True)),
                ('asistencia', models.CharField(max_length=255)),
                ('anotaciones', models.CharField(max_length=255)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='alumno.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='curso.curso')),
            ],
        ),
    ]
